### ISSUE TITLE
Runtime Binary

### ISSUE THREAD

**Issue by rahulc8y** [SoftwareAG/cumulocity-event-image-viewer-widget#5]
If the effort for converting it is low, please consider converting it to a plugin and providing a runtime binary.

Creating a runtime binary for this widget might make it easy for users to install this as an extension package in administration and make use of it in cockpit easily

**Comment by YashPShah-swag** [comment]
Please find the [plugin](https://github.com/SoftwareAG/cumulocity-event-image-viewer-widget-plugin) here.
